---
title: "pbmc_sorted"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# R color brewer Paired, Accent and Dark2 color palettes
zeileis_28 = c(
    "#023fa5", "#7d87b9", "#bec1d4", "#d6bcc0", "#bb7784", "#8e063b", "#4a6fe3",
    "#8595e1", "#b5bbe3", "#e6afb9", "#e07b91", "#d33f6a", "#11c638", "#8dd593",
    "#c6dec7", "#ead3c6", "#f0b98d", "#ef9708", "#0fcfc0", "#9cded6", "#d5eae7",
    "#f3e1eb", "#f6c4e1", "#f79cd4", "navy",
    '#7f7f7f', "#c7c7c7", "#1CE6FF", "#336600"  # these last ones were added,
)


godsnot_102 = c(
    # "#000000",  # remove the black, as often, we have black colored annotation
    "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
    "#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
    "#5A0007", "#809693", "#6A3A4C", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
    "#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100",
    "#DDEFFF", "#000035", "#7B4F4B", "#A1C299", "#300018", "#0AA6D8", "#013349", "#00846F",
    "#372101", "#FFB500", "#C2FFED", "#A079BF", "#CC0744", "#C0B9B2", "#C2FF99", "#001E09",
    "#00489C", "#6F0062", "#0CBD66", "#EEC3FF", "#456D75", "#B77B68", "#7A87A1", "#788D66",
    "#885578", "#FAD09F", "#FF8A9A", "#D157A0", "#BEC459", "#456648", "#0086ED", "#886F4C",
    "#34362D", "#B4A8BD", "#00A6AA", "#452C2C", "#636375", "#A3C8C9", "#FF913F", "#938A81",
    "#575329", "#00FECF", "#B05B6F", "#8CD0FF", "#3B9700", "#04F757", "#C8A1A1", "#1E6E00",
    "#7900D7", "#A77500", "#6367A9", "#A05837", "#6B002C", "#772600", "#D790FF", "#9B9700",
    "#549E79", "#FFF69F", "#201625", "#72418F", "#BC23FF", "#99ADC0", "#3A2465", "#922329",
    "#5B4534", "#FDE8DC", "#404E55", "#0089A3", "#CB7E98", "#A4E804", "#324E72"
)


ggsci_npg <- ggsci::pal_npg()(7)
```



```{r}
library(Seurat)
library(ggplot2)
library(edgeR)
library(patchwork)
library(scmap)


devtools::load_all(path="../../scDECAF")
library(scDECAF)


panglao <- read.delim("../PanglaoDB_markers_27_Mar_2020.tsv")
cellmarker <- read.delim("../all_cell_markers.txt")
```

```{r}
dir_names <- list.dirs("../10X/purifiedpbmc")
dir_names <- grep("hg19", dir_names, value = TRUE)
dir_names <- grep("cd34", dir_names, value = TRUE, invert = TRUE)
celltype_names <- c("B cells", "CD14 Monocytes", #"CD34 cells", 
                    "CD4 T helper", "CD56 NK", "Cytotoxic T cells",
                    "Memory T cells", "Naive CD8 T cells", "Naive CD4 T cells", "Regulatory T cells")

seuratObjs <- list()

for(j in seq_along(dir_names)){

  projName <- celltype_names[j]
  seuratObjs[[projName]] <- CreateSeuratObject(counts = Read10X(dir_names[j])) # , min.features = 100

}



sorted.pbmc <- merge(seuratObjs[[1]],
                  y = Reduce(c,seuratObjs[-1]),
                  add.cell.ids = names(seuratObjs),
                  project = "PBMC-sorted")

sorted.pbmc





sorted.pbmc <- SCTransform(object = sorted.pbmc, verbose = FALSE, variable.features.n = 3000)
sorted.pbmc

dim(x = GetAssayData(object = sorted.pbmc, slot = 'scale.data'))
 


sorted.pbmc <- RunUMAP(object = sorted.pbmc, features = VariableFeatures(object = sorted.pbmc),
                  reduction.key = 'sctUMAP_', reduction.name = 'sctumap')


Idents(sorted.pbmc) <- gsub("(.*)_(.*)","\\1", colnames(sorted.pbmc))
sorted.pbmc$celltype <- gsub("(.*)_(.*)","\\1", colnames(sorted.pbmc))

#save(sorted.pbmc, file="../sorted_pbmc_seuratObj_3k_hvg.RData")

p1 <- DimPlot(sorted.pbmc, cols = "Paired") + theme_void()
```

```{r}
pb_markers <- cellmarker[cellmarker$tissueType %in% c("Peripheral blood"),]
#table(pb_markers$cellName)
pb_markers <- unique(pb_markers)
pb_markers <- split(pb_markers$geneSymbol, as.factor(pb_markers$cellName))



pb_markers <- lapply(pb_markers, FUN=function(x) {
  z <- unlist(strsplit(x, split = ","))
  z <- unique(gsub(" |\\[|\\]","", z))
})


keep <- c(#"Naive CD4+ T cell", "Naive CD8+ T cell",
          "CD8+ T cell", "CD4+ T cell",
          "Natural killer cell"
          #"Regulatory T (Treg) cell",
          #"T cell","T helper cell",
          #"Memory T cell",
          #"B cell",
          #"Fibroblast", 
          #"Plasma cell",
          #"CD16+ dendritic cell"
          #"CD4+ memory T cell","CD4+ T helper cell",
          #"CD8+ cytotoxic T cell"
          #"Monocyte"
          )



pb_markers <- pb_markers[keep]

panlog.sub <- panglao[panglao$organ %in% "Immune system",]
table(panlog.sub$cell.type)

pb_markers2 <- panlog.sub
pb_markers2 <- unique(pb_markers2)
pb_markers2 <- split(pb_markers2$official.gene.symbol, as.factor(pb_markers2$cell.type))

pb_markers2 <- pb_markers2[c("Monocytes",
                             #"Neutrophils", "Eosinophils",
                             #"T helper cells","T memory cells",
                             #"T regulatory cells",
                          #"T cytotoxic cells",
                          "B cells"
                          #"T cells"
                          #"NK cells"
                          )]


 pb_markers <- c(pb_markers, pb_markers2)
#pb_markers <-  pb_markers2
 
 
```


```{r}
dim(x = GetAssayData(object = sorted.pbmc, slot = 'data'))
x <- GetAssayData(object = sorted.pbmc, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values

hvg <- VariableFeatures(object = sorted.pbmc)

target <- genesets2ids(x[match(hvg, rownames(x)),], pb_markers) # x[match(hvg, rownames(x)),]
table(rowSums(target) > 2) 

rownames(target)[rowSums(target) > 2]


head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]
```


```{r}
cell_embeddings <- sorted.pbmc@reductions$sctumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]


x <- as.matrix(x)

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 300, embedding = cell_embeddings,
                   n_components = ncol(target) - 1, max_iter = 2, thresh = 0.5)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

sorted.pbmc$pred_celltype <- preds
Idents(sorted.pbmc) <- sorted.pbmc$pred_celltype
p2 <- DimPlot(sorted.pbmc, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

sorted.pbmc$pred_celltype2 <- preds2
Idents(sorted.pbmc) <- sorted.pbmc$pred_celltype2
p3 <- DimPlot(sorted.pbmc, cols = ggsci_npg) + theme_void() # zeileis_28



#table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

sorted.pbmc <- AddMetaData(sorted.pbmc, pred_scores, "pred_score")
p4 <- FeaturePlot(sorted.pbmc, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

sorted.pbmc <- AddMetaData(sorted.pbmc, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(sorted.pbmc, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

#(p1+p12)/(p2+p3)
#(p1+p3)/(p4+p5)

#cowplot::plot_grid(p1,p3,p4,p5, ncol=2)
cowplot::plot_grid(p1,p3, ncol=2)
```

```{r}

plot(
  getSankey(
    sorted.pbmc$celltype,
    preds2,
    #plot_height = 600
  )
)


#save(ann_res, file="../sorted_pbmc_scDECAF_preds.RData")

```
