---
title: "singleR"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TM Lung 10X
```{r}
# library(scRNAseq)
# as.data.frame(listDatasets())
# ref <- ZilionisLungData('mouse')
# table(ref$`Major cell type`)


# library(celldex)
# hpca.se <- HumanPrimaryCellAtlasData()
# table(hpca.se$label.main)


library(SingleR)
library(SummarizedExperiment)
library(Seurat)

```

Prepare reference (Human Lung Cell Atlas)
```{r}
countdata <- read.csv("../human_lung_cell_atlas/mouse_droplet_TMS_UMIs.csv")
meta <- read.csv("../human_lung_cell_atlas/mouse_droplet_TMS_metadata.csv")

rownames(countdata) <- countdata$X
countdata$X <- NULL


# using Seurat for normalization --- 


refdata <- CreateSeuratObject(counts = countdata)
refdata <- SCTransform(object = refdata, verbose = FALSE, variable.features.n = 3000)
refdata





colData <- DataFrame(meta)
hlca.se <- SummarizedExperiment(assays=list(logcounts=as.matrix(GetAssayData(refdata, "data"))), colData=colData)
```

Prepare test data
```{r}
dir_names <- grep("Lung", list.dirs("../tabula_muris/droplet"), value = TRUE)
seuratObjs <- list()

for(j in seq_along(dir_names)){

  projName <- gsub("(.*)/(.*)/(.*)","\\3", dir_names[j])
  projName <- gsub("Lung-","", projName)
  seuratObjs[[projName]] <- CreateSeuratObject(counts = Read10X(dir_names[j]))

}


bcdata <- merge(seuratObjs[[1]],
                  y = Reduce(c,seuratObjs[-1]),
                  add.cell.ids = names(seuratObjs),
                  project = "lung-10x")

bcdata

bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 3000)
bcdata

# prepare labels
meta <- read.csv("../tabula_muris/annotations_droplet.csv") 
meta <- meta[meta$tissue == "Lung",]

meta$cell_id <- paste0(meta$cell,"-1")

table(meta$cell_ontology_class)

table(is.na(match(meta$cell_id, colnames(bcdata))))
bcdata <- bcdata[,match(meta$cell_id, colnames(bcdata))]


celltypes <- meta$cell_ontology_class
names(celltypes) <- meta$cell_id


tmLung10x <- SummarizedExperiment(assays=list(logcounts=as.matrix(GetAssayData(bcdata, "data"))))

```

```{r}
pred.tmLungs <- SingleR(test = tmLung10x, ref = hlca.se, assay.type.test=1,
    labels = hlca.se$free_annotation)


#save(pred.tmLungs, file = "SingleR_preds_TM_lung_10X.RData")

library(scmap)

load("SingleR_preds_TM_lung_10X.RData")

plot(
  getSankey(
    celltypes,
    pred.tmLungs$labels,
    
    #plot_height = 400
  )
)

```


# PBMC sorted
```{r}
# library(celldex)
# hca <- HumanPrimaryCellAtlasData()
```

PBMC 8k data
```{r}
ref <- CreateSeuratObject(counts = Read10X("../10X/pbmc8k/"))

pbmc_meta <- read.csv("../10X/pbmc8k/pbmc8k_Cole2019_labels.csv")

ref <- ref[,colnames(ref) %in% pbmc_meta$x]
pbmc_meta <- pbmc_meta[match(colnames(ref), pbmc_meta$x),]

ref$celltype <- pbmc_meta$labels

# seurat object
ref <- SCTransform(object = ref, verbose = FALSE, variable.features.n = 3000)

# se object
ref.se <- SummarizedExperiment(assays=list(logcounts=as.matrix(GetAssayData(ref, "data"))))

all(colnames(ref.se) == colnames(ref))


# downsample to 2000 cells ---
set.seed(42)

i <- sample(seq_len(ncol(ref.se)), 2000, replace = FALSE)


ref.se <- ref.se[,i]
```


```{r}
load("../sorted_pbmc_seuratObj_5k_hvg.RData")
hSortedPBMC.se <- SummarizedExperiment(assays=list(logcounts=as.matrix(GetAssayData(sorted.pbmc, "data"))))


pred.sortedPPMC <- SingleR(test = hSortedPBMC.se, ref = ref.se, assay.type.test=1,
    labels = ref$celltype[i])


# save(pred.sortedPPMC, file="SingleR_preds_sorted_pbmc.RData")

plot(
  getSankey(
    gsub("(.*)_(.*)","\\1", colnames(sorted.pbmc)),
    pred.sortedPPMC$labels,
    
    #plot_height = 400
  )
)
```


# Pancreas using Seger as reference and baron as query

```{r}
library(scRNAseq)


baron <- BaronPancreasData('human')
seger <- SegerstolpePancreasData()


library(scran)
library(scater)

clusters <- quickCluster(baron)
baron <- computeSumFactors(baron, clusters=clusters)
summary(sizeFactors(baron))
baron <- logNormCounts(baron)


clusters <- quickCluster(seger)
seger <- computeSumFactors(seger, clusters=clusters)
summary(sizeFactors(seger))
seger <- logNormCounts(seger)


label_isnot_na <- which(!is.na(seger$`cell type`))

pred.baron <- SingleR(test = baron, ref = seger[, label_isnot_na], 
                      #assay.type.test="counts", assay.type.ref = "counts",
    labels = seger$`cell type`[label_isnot_na])


plot(
  getSankey(
    baron$label,
    pred.baron$labels,
    
    #plot_height = 400
  )
)

# save(pred.baron, file="baron_pancreas_SingleR_preds.RData")

```


# Dentate Gyrus

```{r}

## reference----
meta <- read.delim("../cortext_linnarssonlab/GSE104323_metadata_barcodes_24185cells.txt") # appropriate as reference
table(meta$characteristics..cell.cluster)

meta$cell_id <- paste0("X", gsub("-",".", meta$Sample.name..24185.single.cells.))

countdata <- read.delim("../cortext_linnarssonlab/GSE104323_10X_expression_data_V2.tab")
rownames(countdata) <- countdata$cellid
query_labels <- as.character(countdata[2,])[-1]
countdata$cellid <- NULL

refdata <- SingleCellExperiment(assays=list(counts=as.matrix(countdata)))

clusters <- quickCluster(refdata)
refdata <- computeSumFactors(refdata, clusters=clusters)
refdata <- logNormCounts(refdata)



# query -----
countdata <- read.delim("../cortext_linnarssonlab/GSE95315_10X_expression_data_v2.tab") # appropriate as query
table(as.character(countdata[2,]))
query_labels <- as.character(countdata[2,])[-1]
rownames(countdata) <- countdata$cellid
countdata <- countdata[-c(1:2),]

countdata$cellid <- NULL




brain_query <- SingleCellExperiment(assays=list(counts=data.matrix(countdata)))

clusters <- quickCluster(brain_query)
brain_query <- computeSumFactors(brain_query, clusters=clusters)
brain_query <- logNormCounts(brain_query)

# prediction----

pred.brain <- SingleR(test = brain_query, ref = refdata, assay.type.test=1,
    labels = meta$characteristics..cell.cluster[match(colnames(refdata), meta$cell_id)])


plot(
  getSankey(
    query_labels,
    pred.brain$labels,
    
    #plot_height = 400
  )
)

#save(pred.brain, file="brain_preds_singleR.RData")

```
