---
title: "brain_dentate_gyrus"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

zeileis_28 = c(
    "#023fa5", "#7d87b9", "#bec1d4", "#d6bcc0", "#bb7784", "#8e063b", "#4a6fe3",
    "#8595e1", "#b5bbe3", "#e6afb9", "#e07b91", "#d33f6a", "#11c638", "#8dd593",
    "#c6dec7", "#ead3c6", "#f0b98d", "#ef9708", "#0fcfc0", "#9cded6", "#d5eae7",
    "#f3e1eb", "#f6c4e1", "#f79cd4", "navy",
    '#7f7f7f', "#c7c7c7", "#1CE6FF", "#336600"  # these last ones were added,
)


godsnot_102 = c(
    # "#000000",  # remove the black, as often, we have black colored annotation
    "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
    "#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
    "#5A0007", "#809693", "#6A3A4C", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
    "#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100",
    "#DDEFFF", "#000035", "#7B4F4B", "#A1C299", "#300018", "#0AA6D8", "#013349", "#00846F",
    "#372101", "#FFB500", "#C2FFED", "#A079BF", "#CC0744", "#C0B9B2", "#C2FF99", "#001E09",
    "#00489C", "#6F0062", "#0CBD66", "#EEC3FF", "#456D75", "#B77B68", "#7A87A1", "#788D66",
    "#885578", "#FAD09F", "#FF8A9A", "#D157A0", "#BEC459", "#456648", "#0086ED", "#886F4C",
    "#34362D", "#B4A8BD", "#00A6AA", "#452C2C", "#636375", "#A3C8C9", "#FF913F", "#938A81",
    "#575329", "#00FECF", "#B05B6F", "#8CD0FF", "#3B9700", "#04F757", "#C8A1A1", "#1E6E00",
    "#7900D7", "#A77500", "#6367A9", "#A05837", "#6B002C", "#772600", "#D790FF", "#9B9700",
    "#549E79", "#FFF69F", "#201625", "#72418F", "#BC23FF", "#99ADC0", "#3A2465", "#922329",
    "#5B4534", "#FDE8DC", "#404E55", "#0089A3", "#CB7E98", "#A4E804", "#324E72"
)

```

```{r}
library(Seurat)
library(patchwork)
library(ggplot2)
library(uwot)
library(scmap)



#devtools::load_all("../../scDECAF")
library(scDECAF)


panglao <- read.delim("../PanglaoDB_markers_27_Mar_2020.tsv")
cellmarker <- read.delim("../all_cell_markers.txt")


```



```{r}
meta <- read.csv("../tabula_muris/annotations_FACS.csv") 
meta <- meta[meta$tissue %in% c("Brain_Non-Myeloid","Brain_Myeloid"),]



dir_names <- grep("Brain", list.files("../tabula_muris/FACS", full.names = TRUE), value = TRUE)

```

```{r}

# the two GSE datasets to work with are GSE104323 and GSE95315

meta <- read.delim("../cortext_linnarssonlab/GSE104323_metadata_barcodes_24185cells.txt") # appropriate as reference
table(meta$characteristics..cell.cluster)

countdata <- read.delim("../cortext_linnarssonlab/GSE95315_10X_expression_data_v2.tab") # appropriate as query
table(as.character(countdata[2,]))

```

```{r}

celltypes <- as.character(countdata[2,])[-1]

rownames(countdata) <- countdata$cellid
countdata <- countdata[-c(1:2),]

countdata$cellid <- NULL

bcdata <- CreateSeuratObject(counts = countdata)
bcdata$celltype <- celltypes


bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 1000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 

bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata), 
                  reduction.key = 'scumap_', reduction.name = 'scumap')


Idents(bcdata) <- bcdata$celltype



p1 <- DimPlot(bcdata, cols = zeileis_28, order = TRUE) + theme_void()

```




```{r}
brain_markers <- panglao[panglao$organ %in% "Brain", c("cell.type", "official.gene.symbol")]
brain_markers <- unique(brain_markers)
brain_markers <- split(brain_markers$official.gene.symbol, as.factor(brain_markers$cell.type))

# needs human to mouse id conversion
keep <- c("Radial glia cells","Neural stem/precursor cells")


brain_markers <- brain_markers[keep]

brain_markers2 <- cellmarker[cellmarker$tissueType %in% c("Brain", "Cerebellum"), c("cellName", "geneSymbol")]
brain_markers2 <- unique(brain_markers2)
brain_markers2 <- split(brain_markers2$geneSymbol, as.factor(brain_markers2$cellName))


keep2 <- c("Pericyte",
           "Oligodendrocyte progenitor cell",
           "Oligodendrocyte",
           "Neuron",
           "Neuroblast",
           "Microglial cell",
           "Long-projecting GABAergic cell",
           "Ependymal cell",
           "Endothelial cell",
           "Cajal-Retzius cell",
           "Astrocyte")


brain_markers2 <- brain_markers2[keep2]



brain_markers2 <- lapply(brain_markers2, FUN=function(x) {
  z <- unlist(strsplit(x, split = ","))
  z <- gsub(" |\\[|\\]","", z)
})

ms <- read.delim("../../../genomes/DATA/HMD_HumanPhenotype.rpt", header = FALSE)

brain_markers <- lapply(brain_markers, FUN=function(x) {
   ms$V5[match(x, ms$V1)]
})


brain_markers <- c(brain_markers, brain_markers2)
```

```{r}
dim(x = GetAssayData(object = bcdata, slot = 'data'))
x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values

x <- as.matrix(x)

hvg <- VariableFeatures(object = bcdata)



target <- genesets2ids(x[match(hvg, rownames(x)),], brain_markers) # x[match(hvg, rownames(x)),]



colSums(target)



target <- target[,colSums(target) > 0]


head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]
```


```{r}
cell_embeddings <- bcdata@reductions$scumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 30, embedding = cell_embeddings,
                   n_components = ncol(target) - 1, max_iter = 2)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = "Paired") + theme_void() # zeileis_28



table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()



cowplot::plot_grid(p1,p3, ncol=2)

```

```{r}
plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)


plot(
  getSankey(
    bcdata$celltype,
    preds,
    plot_height = 400
  )
)

```

