---
title: "cortex_2014"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

zeileis_28 = c(
    "#023fa5", "#7d87b9", "#bec1d4", "#d6bcc0", "#bb7784", "#8e063b", "#4a6fe3",
    "#8595e1", "#b5bbe3", "#e6afb9", "#e07b91", "#d33f6a", "#11c638", "#8dd593",
    "#c6dec7", "#ead3c6", "#f0b98d", "#ef9708", "#0fcfc0", "#9cded6", "#d5eae7",
    "#f3e1eb", "#f6c4e1", "#f79cd4", "navy",
    '#7f7f7f', "#c7c7c7", "#1CE6FF", "#336600"  # these last ones were added,
)


godsnot_102 = c(
    # "#000000",  # remove the black, as often, we have black colored annotation
    "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
    "#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
    "#5A0007", "#809693", "#6A3A4C", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
    "#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100",
    "#DDEFFF", "#000035", "#7B4F4B", "#A1C299", "#300018", "#0AA6D8", "#013349", "#00846F",
    "#372101", "#FFB500", "#C2FFED", "#A079BF", "#CC0744", "#C0B9B2", "#C2FF99", "#001E09",
    "#00489C", "#6F0062", "#0CBD66", "#EEC3FF", "#456D75", "#B77B68", "#7A87A1", "#788D66",
    "#885578", "#FAD09F", "#FF8A9A", "#D157A0", "#BEC459", "#456648", "#0086ED", "#886F4C",
    "#34362D", "#B4A8BD", "#00A6AA", "#452C2C", "#636375", "#A3C8C9", "#FF913F", "#938A81",
    "#575329", "#00FECF", "#B05B6F", "#8CD0FF", "#3B9700", "#04F757", "#C8A1A1", "#1E6E00",
    "#7900D7", "#A77500", "#6367A9", "#A05837", "#6B002C", "#772600", "#D790FF", "#9B9700",
    "#549E79", "#FFF69F", "#201625", "#72418F", "#BC23FF", "#99ADC0", "#3A2465", "#922329",
    "#5B4534", "#FDE8DC", "#404E55", "#0089A3", "#CB7E98", "#A4E804", "#324E72"
)

blues_oranges <- c("#A6CEE3" ,"#1F78B4", "#FDBF6F","#FF7F00", "#E31A1C", "#6A3D9A","navy")
ggsci_npg <- ggsci::pal_npg()(10)

```

```{r}
library(Seurat)
library(patchwork)
library(ggplot2)
library(uwot)
library(scmap)


#devtools::load_all("../../scDECAF")

library(scDECAF)


panglao <- read.delim("../PanglaoDB_markers_27_Mar_2020.tsv")
cellmarker <- read.delim("../all_cell_markers.txt")

```


# Cortex data 

```{r}


immune_cells_panlog <- panglao[panglao$organ %in% "Brain", c("cell.type", "official.gene.symbol")]
immune_cells_panlog <- unique(immune_cells_panlog)
immune_cells_panlog <- split(immune_cells_panlog$official.gene.symbol, as.factor(immune_cells_panlog$cell.type))




cortex_markers <- cellmarker[cellmarker$tissueType %in% "Brain", c("cellName", "geneSymbol")]
cortex_markers <- unique(cortex_markers)
cortex_markers <- split(cortex_markers$geneSymbol, as.factor(cortex_markers$cellName))

id <- c("Astrocyte","Cajal-Retzius cell","Endothelial cell",
        "Ependymal cell","Microglial cell","Mural cell","Oligodendrocyte")

cortex_markers <- cortex_markers[match(id, names(cortex_markers))]
cortex_markers <- lapply(cortex_markers, FUN=function(x) {
  z <- unlist(strsplit(x, split = ","))
  z <- gsub(" |\\[|\\]","", z)
})


ms <- read.delim("../../../genomes/DATA/HMD_HumanPhenotype.rpt", header = FALSE)

cortex_markers[['Pyramidal cells']] <- ms$V5[match(immune_cells_panlog[['Pyramidal cells']], ms$V1)]
cortex_markers[['Interneurons']] <- ms$V5[match(immune_cells_panlog[["Interneurons"]], ms$V1)]



```

```{r}
cortex <- read.delim("../cortext_linnarssonlab/expression_mRNA_17-Aug-2014.txt", header = FALSE)
cortex <- t(cortex)
table(cortex[,10])

count_data <- cortex[,12:ncol(cortex)]
ROW_names <- count_data[1,]
count_data <- count_data[-c(1:2),]
count_data <- t(as.matrix(count_data))
COL_names <- cortex[-c(1,2),8]
count_data <- apply(count_data, 2, as.numeric)

dim(count_data)

colnames(count_data) <- COL_names
rownames(count_data) <- ROW_names

count_data[1:10,1:10]


meta_data <- data.frame(cortex[-c(1:2),1:10])
colnames(meta_data) <- cortex[2,1:10]

table(meta_data$level1class)
table(meta_data$level2class)

projName <- "cortex_2014"
bcdata <- CreateSeuratObject(counts = count_data, project = projName)
bcdata$celltype <- meta_data$level1class


bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 1000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 

bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata), 
                  reduction.key = 'scumap_', reduction.name = 'scumap')


Idents(bcdata) <- bcdata$celltype



p1 <- DimPlot(bcdata, cols = blues_oranges, order = TRUE) + theme_void()

Idents(bcdata) <- meta_data$level2class
p12 <- DimPlot(bcdata, cols = godsnot_102, order = TRUE) + theme_void()

p1 + p12

```

Note this is a mouse dataset
```{r}
dim(x = GetAssayData(object = bcdata, slot = 'data'))
x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values

x <- as.matrix(x)

hvg <- VariableFeatures(object = bcdata)

target <- genesets2ids(x[match(hvg, rownames(x)),], cortex_markers) 



xhvg <- x[match(hvg, rownames(x)), ]
xhvg <- xhvg[match(rownames(target), rownames(xhvg)),]


###############
## select gene sets based on information content
################
## cell-wise L1 normalisation
L1 <- apply(xhvg, 2, FUN=function(x) x/sum(abs(x)))



entropies <- apply(target, 2, FUN=function(x) {
  p <- rowMeans(as.matrix(L1[x==1,]))
  -sum(p*log(p))
})


entropies



# using entropy (information content) as a measure of gene set irrelevance
entropies <- entropies/max(entropies)
target <- target[,entropies > 0.1]





head(target)
dim(target)



xt <- x[match(rownames(target), rownames(x)),]
```



```{r}
cell_embeddings <- bcdata@reductions$scumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 100, embedding = cell_embeddings,
                   n_components = ncol(target) - 1, max_iter = 2)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = ggsci_npg) + theme_void() # zeileis_28



table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

(p1+p12)/(p2+p3)
(p1+p3)/(p4+p5)

# cowplot::plot_grid(p1,p3,p4,p5, ncol=2)
cowplot::plot_grid(p1,p3, ncol=2)
```


```{r}
plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)


plot(
  getSankey(
    bcdata$celltype,
    preds,
    plot_height = 400
  )
)

```

