---
title: "pancreas_datasets"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# R color brewer Paired, Accent and Dark2 color palettes
zeileis_28 = c(
    "#023fa5", "#7d87b9", "#bec1d4", "#d6bcc0", "#bb7784", "#8e063b", "#4a6fe3",
    "#8595e1", "#b5bbe3", "#e6afb9", "#e07b91", "#d33f6a", "#11c638", "#8dd593",
    "#c6dec7", "#ead3c6", "#f0b98d", "#ef9708", "#0fcfc0", "#9cded6", "#d5eae7",
    "#f3e1eb", "#f6c4e1", "#f79cd4", "navy",
    '#7f7f7f', "#c7c7c7", "#1CE6FF", "#336600"  # these last ones were added,
)


godsnot_102 = c(
    # "#000000",  # remove the black, as often, we have black colored annotation
    "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
    "#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
    "#5A0007", "#809693", "#6A3A4C", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
    "#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100",
    "#DDEFFF", "#000035", "#7B4F4B", "#A1C299", "#300018", "#0AA6D8", "#013349", "#00846F",
    "#372101", "#FFB500", "#C2FFED", "#A079BF", "#CC0744", "#C0B9B2", "#C2FF99", "#001E09",
    "#00489C", "#6F0062", "#0CBD66", "#EEC3FF", "#456D75", "#B77B68", "#7A87A1", "#788D66",
    "#885578", "#FAD09F", "#FF8A9A", "#D157A0", "#BEC459", "#456648", "#0086ED", "#886F4C",
    "#34362D", "#B4A8BD", "#00A6AA", "#452C2C", "#636375", "#A3C8C9", "#FF913F", "#938A81",
    "#575329", "#00FECF", "#B05B6F", "#8CD0FF", "#3B9700", "#04F757", "#C8A1A1", "#1E6E00",
    "#7900D7", "#A77500", "#6367A9", "#A05837", "#6B002C", "#772600", "#D790FF", "#9B9700",
    "#549E79", "#FFF69F", "#201625", "#72418F", "#BC23FF", "#99ADC0", "#3A2465", "#922329",
    "#5B4534", "#FDE8DC", "#404E55", "#0089A3", "#CB7E98", "#A4E804", "#324E72"
)

```



```{r}
library(scRNAseq)

as.data.frame(listDatasets())

baron <- BaronPancreasData('human')
xin <- XinPancreasData()
seger <- SegerstolpePancreasData()
muraro <- MuraroPancreasData()
law <- LawlorPancreasData()
# muraro and one more
```

```{r}
library(Seurat)
library(GEOquery)
library(edgeR)
library(patchwork)
library(ggplot2)
library(scmap)


# devtools::load_all(path="../../scDECAF")
devtools::load_all(path="../scDECAF")
# library(scDECAF)


# panglao <- read.delim("../PanglaoDB_markers_27_Mar_2020.tsv")
# cellmarker <- read.delim("../all_cell_markers.txt")

panglao <- read.delim("../benchmarking/PanglaoDB_markers_27_Mar_2020.tsv")
cellmarker <- read.delim("../benchmarking/all_cell_markers.txt")
```

# Baron 
```{r}
projName <- "baron_pancreas"
bcdata <- CreateSeuratObject(counts = assay(baron, 'counts'), project = projName)
bcdata$celltype <- baron$label

bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 2000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 

bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata),
                  reduction.key = 'sctUMAP_', reduction.name = 'sctumap')


bcdata <- RunPCA(object = bcdata, features = VariableFeatures(object = bcdata),
                  reduction.key = 'sctPCA_', reduction.name = 'sctpca')


Idents(bcdata) <- bcdata$celltype



p1 <- DimPlot(bcdata, cols = zeileis_28) + theme_void()
```


```{r}
immune_cells_panlog <- panglao[panglao$organ %in% "Immune system", c("cell.type", "official.gene.symbol")]
immune_cells_panlog <- unique(immune_cells_panlog)
immune_cells_panlog <- split(immune_cells_panlog$official.gene.symbol, as.factor(immune_cells_panlog$cell.type))

immune_cells_panlog <- immune_cells_panlog[c("T cytotoxic cells",
                                             "Macrophages",
                                             "Mast cells",
                                             "T cells")]



pancreas_markers <- panglao[panglao$organ %in% c("Pancreas","Vasculature"), c("cell.type", "official.gene.symbol")]
#table(pb_markers$cellName)
pancreas_markers <- unique(pancreas_markers)
pancreas_markers <- split(pancreas_markers$official.gene.symbol, as.factor(pancreas_markers$cell.type))

pancreas_markers <- pancreas_markers[grep("Pericytes", names(pancreas_markers), invert = TRUE)]


immune_cells_panlog <- c(immune_cells_panlog, pancreas_markers)


dim(x = GetAssayData(object = bcdata, slot = 'data'))
x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values

hvg <- VariableFeatures(object = bcdata)

cell_embeddings <- bcdata@reductions$sctumap@cell.embeddings
# cell_embeddings <- bcdata@reductions$sctpca@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(x), rownames(cell_embeddings)),]


x <- as.matrix(x)


## apply geneset selection

# selected_gs <- pruneGenesets(data = x, genesetlist = immune_cells_panlog,
#                              hvg = hvg, embedding = cell_embeddings,
#                              min_gs_size = 3, lambda = exp(-6.5))
# 
# 
# 
# as.character(selected_gs)




# target <- genesets2ids(x[match(hvg, rownames(x)),], immune_cells_panlog[selected_gs]) # x[match(hvg, rownames(x)),]
target <- genesets2ids(x[match(hvg, rownames(x)),], immune_cells_panlog)
 
colSums(target)



head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]

```

```{r}
# cellasssign?
library(cellassign)
library(SingleCellExperiment)

# x2 <- GetAssayData(object = bcdata, slot = 'counts')
# x2 <- x2[match(rownames(target), rownames(x2)),]
# x2 <- as.matrix(x2)


load("/stornext/General/data/academic/lab_davis/Yi_Soroor/benchmarking/cellassign_data.RData")


sce <- SingleCellExperiment(list(counts = x2))

fit <- em_result <- cellassign(sce,
                                marker_gene_info = target,
                                s = colSums(SummarizedExperiment::assay(sce, "counts")),
                                # learning_rate = 1e-2,
                               learning_rate = 0.3,
                                shrinkage = TRUE,
                               #threads = 10,
                               #max_iter_em = 10,
                                verbose = TRUE)
```

```{r}

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 10, embedding = cell_embeddings,
                   n_components = ncol(target) - 1, max_iter = 2,
                   thresh = 0.5)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = "Paired") + theme_void() # zeileis_28



table(preds2, bcdata$celltype)
# save(ann_res, file = "../benchmarking/RData_files_for_method_evals/0821_baron_scDECAF.RData")

pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

#(p1+p12)/(p2+p3)
(p1+p3)/(p4+p5)

# cowplot::plot_grid(p1,p3,p4,p5, ncol=2)
cowplot::plot_grid(p1,p3)

```

```{r}
plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)


plot(
  getSankey(
    bcdata$celltype,
    preds,
    plot_height = 400
  )
)

```


<!-- The rest of the document runs scDECAF on other pancreatic datasets not included in paper analyses -->
# Xin et al.

```{r}
projName <- "xin_pancreas"
count_data <- assay(xin, 'rpkm')
rownames(count_data) <- rowData(xin)$symbol

bcdata <- CreateSeuratObject(counts = count_data, project = projName)
bcdata$celltype <- xin$cell.type



bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 1000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 


bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata), reduction.key = 'scumap_', reduction.name = 'scumap')


Idents(bcdata) <- bcdata$celltype



p1 <- DimPlot(bcdata, cols = godsnot_102) + theme_void()
```

```{r}
dim(x = GetAssayData(object = bcdata, slot = 'data'))
x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values

hvg <- VariableFeatures(object = bcdata)

target <- genesets2ids(x[match(hvg, rownames(x)),], immune_cells_panlog) # x[match(hvg, rownames(x)),]
 
xhvg <- x[match(hvg, rownames(x)),]
xhvg <- xhvg[match(rownames(target), rownames(xhvg)),]



###############
## select gene sets based on information content
################
## cell-wise L1 normalisation
L1 <- apply(xhvg, 2, FUN=function(x) x/sum(abs(x)))



entropies <- apply(target, 2, FUN=function(x) {
  p <- rowMeans(as.matrix(L1[x==1,]))
  -sum(p*log(p))
})


entropies[order(entropies, decreasing = TRUE)]

##################
# based on variance explained
###################
gsmat <- genesets2ids(x, immune_cells_panlog)


xpearson <- x[match(hvg, rownames(x)),]
xpearson <- as.matrix(xpearson)
xpearson <- xpearson[match(rownames(gsmat), rownames(xpearson)),]


# xpearson <- x[match(rownames(gsmat), rownames(x)),]

mean_pearson_rss <- apply(gsmat, 2, FUN=function(x) {
  # note in seurat these are pearson residulas
  p <- rowSums(as.matrix(xpearson[x==1,]), na.rm = TRUE)
  mean(p)
})



# this dataset is an example where pearson residuals work well
z <- mean_pearson_rss
ztrim <- quantile(z, probs = 0.6)
z[z >= ztrim]



colSums(target)



target <- target[,z >= ztrim]


head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]
```

```{r}
cell_embeddings <- bcdata@reductions$scumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 30, embedding = cell_embeddings,
                   n_components = ncol(target) - 1, max_iter = 2)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

#(p1+p12)/(p2+p3)
(p1+p3)/(p4+p5)

cowplot::plot_grid(p1,p3,p4,p5, ncol=2)

```

```{r}
plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)


plot(
  getSankey(
    bcdata$celltype,
    preds,
    plot_height = 400
  )
)

```


# Segerslope et al.

```{r}

# Data pre-processing ---
projName <- "seger_pancreas"
count_data <- assay(seger, 'counts')


bcdata <- CreateSeuratObject(counts = count_data, project = projName)
bcdata$celltype <- seger$`cell type`


bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 1000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 



bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata), reduction.key = 'sctUMAP_', reduction.name = 'scumap')

Idents(bcdata) <- bcdata$celltype

p1 <- DimPlot(bcdata, cols = godsnot_102) + theme_void()


# celltype prediction----

x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values
x <- as.matrix(x)



hvg <- VariableFeatures(object = bcdata)

target <- genesets2ids(x[match(hvg, rownames(x)),], immune_cells_panlog) # x[match(hvg, rownames(x)),]
 
head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]

cell_embeddings <- bcdata@reductions$scumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 30, embedding = cell_embeddings,
                   n_components = ncol(target) - 1)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

#(p1+p12)/(p2+p3)
(p1+p3)/(p4+p5)

cowplot::plot_grid(p1,p3,p4,p5, ncol=2)

plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)

```

# Muraro et al.

```{r}
# Data pre-processing ---
projName <- "muraro_pancreas"
count_data <- assay(muraro, 'counts')
rownames(count_data) <- rowData(muraro)$symbol

bcdata <- CreateSeuratObject(counts = count_data, project = projName)
bcdata$celltype <- muraro$label


bcdata <- SCTransform(object = bcdata, verbose = FALSE, variable.features.n = 1000)
bcdata

dim(x = GetAssayData(object = bcdata, slot = 'scale.data'))
 



bcdata <- RunUMAP(object = bcdata, features = VariableFeatures(object = bcdata), 
                  metric="euclidean", min.dist = 0.5, seed.use = 0,
                  n.neighbors = 30L,
                  reduction.key = 'sctSNE_', reduction.name = 'scumap')


Idents(bcdata) <- bcdata$celltype

p1 <- DimPlot(bcdata, cols = "Paired") + theme_void()


# repeat umap using uwot package -------



# celltype prediction----

x <- GetAssayData(object = bcdata, slot = 'data') # same as x <- bcdata[["SCT"]]@data, contains log-normalised values
x <- as.matrix(x)



hvg <- VariableFeatures(object = bcdata)

target <- genesets2ids(x[match(hvg, rownames(x)),], immune_cells_panlog) # x[match(hvg, rownames(x)),]


xhvg <- x[match(hvg, rownames(x)),]
xhvg <- xhvg[match(rownames(target), rownames(xhvg)),]



###############
## select gene sets based on information content
################
## cell-wise L1 normalisation
L1 <- apply(xhvg, 2, FUN=function(x) x/sum(abs(x)))



entropies <- apply(target, 2, FUN=function(x) {
  p <- rowMeans(as.matrix(L1[x==1,]))
  -sum(p*log(p))
})


entropies[order(entropies, decreasing = TRUE)]

##################
# based on variance explained
###################
gsmat <- genesets2ids(x, immune_cells_panlog)


xpearson <- x[match(hvg, rownames(x)),]
xpearson <- as.matrix(xpearson)
xpearson <- xpearson[match(rownames(gsmat), rownames(xpearson)),]


# xpearson <- x[match(rownames(gsmat), rownames(x)),]

mean_pearson_rss <- apply(gsmat, 2, FUN=function(x) {
  # note in seurat these are pearson residulas
  p <- rowSums(as.matrix(xpearson[x==1,]), na.rm = TRUE)
  mean(p)
})



# this dataset is an example where pearson residuals work well
z <- mean_pearson_rss
ztrim <- quantile(z, probs = 0.3)
z[z >= ztrim]



colSums(target)


# target <- target[,entropies > 0.1]
#target <- target[, colSums(target) > 10 & entropies > 0.1]
target <- target[,z >= ztrim] 
head(target)
dim(target)

xt <- x[match(rownames(target), rownames(x)),]

cell_embeddings <- bcdata@reductions$scumap@cell.embeddings
cell_embeddings <- cell_embeddings[match(colnames(xt), rownames(cell_embeddings)),]

ann_res <- scDECAF(data = x, gs = target, standardize = TRUE, 
                   hvg = hvg, k = 30, embedding = cell_embeddings,
                   n_components = ncol(target) - 1)


preds <- ann_res$pred_celltype
names(preds) <- ann_res$cell

bcdata$pred_celltype <- preds
Idents(bcdata) <- bcdata$pred_celltype
p2 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



preds2 <- ann_res$reassigned_celltype
names(preds2) <- ann_res$cell

bcdata$pred_celltype2 <- preds2
Idents(bcdata) <- bcdata$pred_celltype2
p3 <- DimPlot(bcdata, cols = godsnot_102) + theme_void() # zeileis_28



table(preds2, bcdata$celltype)


pred_scores <- ann_res$uncertainty
names(pred_scores) <- ann_res$cell

bcdata <- AddMetaData(bcdata, pred_scores, "pred_score")
p4 <- FeaturePlot(bcdata, features = "pred_score", cols = c( "red", "blue"),
                 pt.size = 0.05) + theme_void()


nn_preserve <- ann_res$prop_neighbourhood_preserved
names(nn_preserve) <- ann_res$cell

bcdata <- AddMetaData(bcdata, nn_preserve, "nn_preserve")
p5 <- FeaturePlot(bcdata, features = "nn_preserve", cols = c( "white", "red"),
                 pt.size = 0.05) + theme_void()

#(p1+p12)/(p2+p3)
(p1+p3)/(p4+p5)

cowplot::plot_grid(p1,p3,p4,p5, ncol=2)

plot(
  getSankey(
    bcdata$celltype,
    preds2,
    plot_height = 400
  )
)

```